### ISSUE TITLE
Need to add user-created files and directories to .gitignore

### ISSUE THREAD

**Issue by wunderhund** [sandialabs/dr_robot#11]
In the normal course of using the program, various directories and files get created that contain information gathered by the end user. These files should never be committed or pushed to the repo, so they should be included in the `.gitignore`:
```
» git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	configs/user_config.json
	dbs/
	docker_buildfiles/Dockerfile.Aquatone
	docker_buildfiles/Dockerfile.Sublist3r
	output/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Sandarmann** [comment]
Added directories that contain user output as well as user created temp files to .gitignore
b51dbbb4b92e902ec3a4e22e0ffe9df8718c2793

**Comment by l50** [comment]
Added, thanks for the issue!
