### ISSUE TITLE
Add massdns support

### ISSUE THREAD

**Issue by l50** [sandialabs/dr_robot#20]
https://github.com/blechschmidt/massdns

**Comment by Sandarmann** [comment]
What domain name resolvers should be used by default? In the dockerfile we can have an echo command to build the file such that users may configure what resolvers massdns users.

**Comment by l50** [comment]
This list looks good: https://gist.github.com/jhaddix/86a06c5dc309d08580a018c66354a056

**Comment by Sandarmann** [comment]
Would it be worth adding a folder for additional material so that we can track files such as the one you posted, in case it were to ever be removed?  Otherwise we can link in directly to that file via wget.

**Comment by l50** [comment]
That's not a bad idea.
