### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by meetgyn** [sandialabs/dr_robot#25]
**I can not install with python3.7. Does it only work on python3.6?**

dr_robot# pipenv install  && pipenv shell
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python

**Comment by Sandarmann** [comment]
Hi @meetgyn, by default Dr.ROBOT has the version set to 3.6. If you would like to run with 3.7 you can switch the version from 3.6 to 3.7 within the pipfile then rerun the same steps you listed above.

This tool does run using 3.7 but it hasn't been fully tested with that version in mind.

**Comment by l50** [comment]
@meetgyn has your issue been resolved?
