### ISSUE TITLE
Duplicate HTTPScreenshot containers

### ISSUE THREAD

**Issue by l50** [sandialabs/dr_robot#3]
I started by running ```python drrobot.py <domain> gather -sub -aqua```, which appeared to be successful. 

I followed this with ```python drrobot.py <domain> inspect -http -eye```, which introduced the issue of standing up duplicate HTTPScreenshot containers. 

Running using Python 3.6.5

**Comment by Sandarmann** [comment]
Resolved. e40ceb2dd969a82ca4e7b6226710fb5c2540ad28
