### ISSUE TITLE
Issue when running with fresh clone

### ISSUE THREAD

**Issue by l50** [sandialabs/dr_robot#51]
This error came up with a fresh clone:
```
drrobot gather -sub -aqua -shodan -sfinder -amass -arin TARGET

Beginning gather
[!] Value Error thrown. Check error log for details
[!] Value Error thrown. Check error log for details
[#] Docker image Sublist3r, building...: : 1it [00:02,  2.01s/it]
[#] Docker image Amass, building...: : 1it [00:02,  2.01s/it]
[#] Docker image Aquatone, building...: : 1it [00:02,  2.01s/it]]
[#] Docker image Subfinder, building...: : 1it [00:02,  2.01s/it]
[#] Docker container Sublist3r, running...: : 7it [00:14,  2.02s/it]
[#] Docker container Subfinder, running...: : 44it [01:28,  2.01s/it]
[#] Docker container Amass, running...: : 74it [02:28,  2.01s/it]it]]
[#] Docker container Aquatone, running...: : 266it [08:54,  2.01s/it]
[!] File shodan.txt does not exist, verify scan results
[!] File arin.txt does not exist, verify scan results
[!] can't pickle _thread.RLock objects
```

Unfortunately, the Value Errors are not easy to find out more information about. Additionally, no output is generated.

**Comment by l50** [comment]
Arin appears to be one of the problematic containers.

**Comment by l50** [comment]
Same issue with less tools being used:
```
(dr_robot) λ the-new-dawn dr_robot → λ git master → drrobot gather -sub -amass TARGET
Beginning gather
[#] Docker image Sublist3r, building...: : 1it [00:02,  2.01s/it]
[#] Docker image Amass, building...: : 1it [00:02,  2.01s/it]
[#] Docker container Sublist3r, running...: : 7it [00:14,  2.01s/it]
[#] Docker container Amass, running...: : 83it [02:46,  2.01s/it]
[!] can't pickle _thread.RLock objects
```

**Comment by l50** [comment]
Not even working with just one tool:
```
drrobot gather -amass TARGET
Beginning gather
[#] Docker image Amass, building...: : 1it [00:02,  2.00s/it]
[#] Docker container Amass, running...: : 83it [02:46,  2.01s/it]
[!] can't pickle _thread.RLock objects
```

**Comment by CrimsonK1ng** [comment]
What version of Python were you using at the time of running? Could you try destroying the previously built containers and having a full rebuild done for them ?

**Comment by l50** [comment]
I was using Python 3.6.9. Yep, same problem:
```
drrobot gather -amass TARGET
Beginning gather
[#] Docker image Amass, building...: : 31it [01:02,  2.00s/it]
[#] Docker container Amass, running...: : 81it [02:42,  2.01s/it]
[!] can't pickle _thread.RLock objects
```

**Comment by CrimsonK1ng** [comment]
Does this happen once the container running finishes? I think this might be related to the multiprocessing for aggregation that I am doing. I could look at changing this. I am not sure what may be causing the pickling issue exactly.

**Comment by CrimsonK1ng** [comment]
I will send push a branch for you to try and see if that helps resolve the error.

**Comment by l50** [comment]
Branch works, let's get a PR going once we know that the changes don't affect any other python 3 versions.

**Comment by jamesjguthrie** [comment]
I have this same issue after cloning the repo on a fresh Kali instance in WSL today.
Beginning gather
[!] Value Error thrown. Check error log for details
[!] Value Error thrown. Check error log for details
[#] Docker image Aquatone, building...: : 1it [00:02,  2.00s/it]
[#] Docker image Sublist3r, building...: : 1it [00:02,  2.00s/it]
[#] Docker image Subfinder, building...: : 1it [00:02,  2.00s/it]
[#] Docker image Amass, building...: : 1it [00:02,  2.00s/it]
[!] Error building Aquatone. Check logs
[!] Error building Sublist3r. Check logs
[!] Error building Subfinder. Check logs
[!] Error building Amass. Check logs
[!] File shodan.txt does not exist, verify scan results
[!] File arin.txt does not exist, verify scan results
[*] Gather complete


Where are the logs?

**Comment by CrimsonK1ng** [comment]
@jamesjguthrie  Logs can be found under the  ~/.drrobot directory in your home folder. There are two files .err and .dbg. Look in the .err file. I can work with you to get it running.

**Comment by jamesjguthrie** [comment]
@CrimsonK1ng seems to be a permissions issue

2019-11-13 13:47:32,538 {/home/jabo/dr_robot/src/robot_api/api/dockerize.py:155}:       [!] Output directory could not be created, please verify permissions
Traceback (most recent call last):
  File "/home/jabo/.local/share/virtualenvs/dr_robot-olFvG74b/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/jabo/.local/share/virtualenvs/dr_robot-olFvG74b/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/jabo/.local/share/virtualenvs/dr_robot-olFvG74b/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by CrimsonK1ng** [comment]
Can you rerun once more to see if this error happens again? The permissions issue stems from it not finding the ~/.drrobot directory which it needs to mount volumes.

**Comment by jamesjguthrie** [comment]
Same error three times. This is the first error in the log but it’s followed by more ‘no such file or directory’ errors.

**Comment by CrimsonK1ng** [comment]
Thanks for trying that. 

Could you try just ```rm -rf ~/.drrobot``` and rerunning the tool. That should recreate the directory structure and remove the permissions issue.

**Comment by jamesjguthrie** [comment]
I did that and reran `pipenv install && pipenv shell`
Same problem.

**Comment by CrimsonK1ng** [comment]
So I went through the steps of spinning up a Kali virtual machine and installing the tool. I was unable to recreate the same issue. My steps were as follows:

1. Install docker-ce (latest version is 19.03.4)
2. Clone repository
3. I ran ```pipenv sync && pipenv shell``` the sync just uses the lock file for instillation
4. ```drrobot gather -sub <target>```

There was no error for me but I would like to verify some things with you:

1. Is your current user in the docker group?
2. When you look in the **drrobot** folder created in your home are the permissions set correctly?

**Comment by jamesjguthrie** [comment]
Thanks for helping me @CrimsonK1ng. My problem was that I had docker.io installed and not the Community Edition. I removed docker.io and installed Docker for Windows following this guide https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly.

dr_robot_ is working fine now.

**Comment by CrimsonK1ng** [comment]
@jamesjguthrie that's great! If you run into anymore problems feel free to create another issue and I will help as I can.
