### ISSUE TITLE
Aggregation doesn't work with latest version

### ISSUE THREAD

**Issue by l50** [sandialabs/dr_robot#8]
Aggregation folder is empty after running gather:
```python drrobot.py <target> gather -sub -aqua```

However, upon running inspect it works. Is this intended functionality? I figured that the aggregation step should happen during the gather phase, but perhaps I'm mistaken.

**Comment by Sandarmann** [comment]
Will be fixed in the up coming release. Was only dumping during inspection phase

**Comment by Sandarmann** [comment]
bc8e8a64aebc816c48b58857f765d94c9e2ab8f5
